sudo: required
services:
  - docker
  
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build --no-cache -t bse666/rpi-mpd .
- docker run --name mpd -d bse666/rpi-mpd
- docker ps -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag bse666/rpi-mpd bse666/rpi-mpd:$TAG
    docker push bse666/rpi-mpd:$TAG
    docker push bse666/rpi-mpd
  fi
